name: storage_bugs
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  about: ^2.1.3
  another_stepper: ^1.1.6
  avatar_glow: ^3.0.1
  cached_network_image: ^3.3.1
  cloud_firestore: ^4.15.5
  cloud_functions: ^4.6.5
  comment_tree: ^0.3.0
  custom_navigation_bar: ^0.8.2
  date_picker_timeline: ^1.2.3
  date_time_format: ^2.0.1
  enum_to_string: ^2.0.1
  equatable: ^2.0.3
  faker: ^2.0.0
  favorite_button: ^0.0.4
  feedback: ^3.0.0
  feedback_sentry: ^3.0.0
  firebase_analytics: ^10.8.6
  firebase_auth: ^4.17.5
  firebase_core: ^2.25.4
  firebase_crashlytics: ^3.4.15
  firebase_database: ^10.4.6
  firebase_messaging: ^14.7.16
  firebase_remote_config: ^4.3.14
  firebase_storage: ^11.6.6
  flex_color_scheme: ^7.3.1

  flutter:
    sdk: flutter

  flutter_cache: ^0.1.0
  flutter_chat_types: ^3.6.0
  flutter_chat_ui: ^1.6.12
  flutter_datetime_picker_plus: ^2.1.0
  flutter_dotenv: ^5.0.2
  flutter_firebase_chat_core: ^1.6.3
  flutter_image_compress: ^2.1.0
  flutter_local_notifications: ^16.3.2
  flutter_markdown: ^0.6.19
  flutter_multi_formatter: ^2.12.4
  flutter_polyline_points: ^2.0.0
  flutter_rating_bar: ^4.0.1
  flutter_slidable: ^3.0.1
  flutter_stripe: ^10.0.0
  flutter_svg: ^2.0.9
  geocoding: ^2.1.1
  geoflutterfire2: ^2.3.11
  geolocator: ^11.0.0
  get: ^4.6.6
  get_storage: ^2.0.3
  google_fonts: ^6.1.0
  google_maps_flutter: ^2.5.3
  google_sign_in: ^6.2.1
  grouped_list: ^5.0.1
  http: ^1.2.0
  iconify_flutter_plus: ^1.0.3
  image: ^4.1.7
  image_picker: ^1.0.7
  intl: ^0.18.1
  location: ^5.0.3
  logger: ^2.0.2+1
  lottie: ^3.0.0
  material_segmented_control: ^5.0.0
  mime: ^1.0.5
  mocktail: ^1.0.3
  package_info_plus: ^5.0.1
  path: ^1.8.3
  path_provider: ^2.1.2
  percent_indicator: ^4.2.2
  permission_handler: ^11.3.0
  photo_view: ^0.14.0
  pull_to_refresh: ^2.0.0
  retry: ^3.1.2
  rxdart: ^0.27.3
  sentry_flutter: ^7.16.1
  share_plus: ^7.2.2
  sign_in_with_apple: ^5.0.0
  smooth_page_indicator: ^1.0.0+2
  solid_bottom_sheet: ^0.1.10
  stack_trace: ^1.11.1
  timeago: ^3.6.1
  tuple: ^2.0.0
  uni_links: ^0.5.1
  url_launcher: ^6.2.4
  uuid: ^4.3.3

dev_dependencies:
  csv: ^5.1.1
  dart_code_metrics_presets: ^2.9.0
  flutter_lints: ^3.0.1

  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
